### ISSUE TITLE
Coordinate Descent

### ISSUE THREAD

**Issue by tolgabirdal** [NicolasBoumal/manopt#21]
@NicolasBoumal,

Is there a quick workaround for having a solver that alternatively minimizes the parameters X={x_i}_i on a product manifold? I am talking about for instance a trust-region solver that can perform alternating updates between two matrices one on Stiefel and one on EDM. There might be two ways to accomplish this: (1) Tangent Subspace Descent as in (https://arxiv.org/pdf/1912.10627.pdf) or (2) Running one step of update per each manifold (and thus x_i) in a sequential manner.

**Comment by NicolasBoumal** [comment]
Hello Tolga,

There's nothing built-in for that in Manopt, but it should be quite easy to implement your second suggestion. You'd simply write a loop within which you'd define an optimization problem in the first variable, call trust regions or something for a few steps (check options to limit iterations), then define the optimization problem in the second variable and call a solver on that. Each time, you'd warm start. You could even write a generic solver for this kind of coordinate descent on product manifolds.

Manopt.jl (Julia version) may have much more to offer because the lead author (Ronny Bergmann) did a lot of work on manifold-valued image processing, where this kind of algorithms are quite important. His papers may also give additional info on how to get this right.

As for your first suggestion: I didn't know they paper (thanks for sharing) but have seen a number of papers in that spirit in the last 9 months. It's a bit more tricky to implement because you need to differentiate the retraction or the exponential, but if you're happy to do that, then I think it's interesting. For certain manifolds, it should even be practical.

**Comment by tolgabirdal** [comment]
Thanks for the thought Nicolas! I wanted to avoid the overhead associated to re-initializing the solvers everytime. It is a good idea to warm-start though. I was implementing a custom solver that takes a cell-array of x0 and a problem with product manifold. In the cost function I plan to output multiple gradients as a cell array. I would begin by modifying steepestdescent (initially) to perform this - in a nature similar to optimization on a product manifold. I am not sure if this is the best way of course but would that work?

**Comment by kellertuer** [comment]
For cell arrays you have to be very careful with performance. It might kill that directly (even compared to reinitialisation).

* Do you have a product manifold with just 2 manifolds that you wan to alternate over or even more? 
* Do you want to cyclicly iterate through them then or in a random order?
* Do your product elements have the same base manifold, so is it maybe even a power manifold? then you could store your data in a higher dimensional array, that would be better performance-wise.

My Matlab skills are growing a little rusty (thanks for the Julia adverts :) ) but maybe the cyclic proximal point might be a start https://github.com/kellertuer/MVIRT/blob/master/algorithms/cyclicProximalPoint.m
which cycles (linearly or randomly) through proximal point evaluations (though on same data not on elements).

**Comment by tolgabirdal** [comment]
Thanks Ronny for referring to the proximal point methods. I will also try to see how this can be used. To answer your questions:

1. The question is more general than the specific case. In my current application I am optimizing on a product manifold of two manifolds: (1) an EDM, (2) a power manifold.
2. It is better if the user can specify the order as this information is available during problem formulation.
3. Nope. Not in general. We could always optimize for specific cases, but let's try to keep things general.

**Comment by kellertuer** [comment]
Then I fear you have to use a cell array, or write a quite advanced array-implementation of a product manifold: you could vectorise all submanidfolds points/tangents for storage and reshape them after access. That might be (by far) faster then cell arrays, but also a little technical to implement.

**Comment by tolgabirdal** [comment]
Right. That would also require reshaping in the cost/gradient evaluations, something I would also like to avoid if possible.

**Comment by kellertuer** [comment]
Thanks for the explanation, I was not aware of the name EDM (and still have to look at the SPD fixed Rank).
