### ISSUE TITLE
Hyperbolicfactory: dist computation

### ISSUE THREAD

**Issue by bamdevm** [NicolasBoumal/manopt#23]
Hello Nicolas, 
The compuations of acosh(-mink_inners) is not same as 2*asinh(.5*mink_norms). We should use 
Regards,
Bamdev

**Comment by NicolasBoumal** [comment]
Hello Bamdev,

With the current code (which uses "2asinh(.5mink_norms)"), this test code works fine:

`M = hyperbolicfactory(5);
x = M.rand();
v = M.randvec(x);
t = rand(1);
y = M.exp(x, v, t);
M.dist(x, y) - t % machine precision zero
M.log(x, y) - t*v % machine precision zero`

But the comments in the Matlab code were confusing: they just said that it would be equivalent to use acosh(-mink_inners), meaning the inner products between X and Y, whereas in the actual code min_inners is defined as inner products between U and U, with U = X-Y.

I'll change the comments, but please let me know if you had something different in mind.

**Comment by NicolasBoumal** [comment]
By the way, this test is implemented in checkmanifold(), easily callable as follows:

`clear all; close all; clc;`
`M = hyperbolicfactory(5, 3);`
`checkmanifold(M);`

It automatically runs this distance test for various distances from 1e-8 to 1e1, making it easy to spot the variable precision for the two formulas.

**Comment by bamdevm** [comment]
Can we check how different are the expressions i) acosh(-<X, Y>_L) and ii) asinh(-<U, U>_L)? I had found them giving different answers for small values of distances.

**Comment by bamdevm** [comment]
Popular optimization problems on the hyperbolic manifold would include some kind of minimization of hyperbolic distance. To that end, the choice of the dist expressions may have an impact. Any thoughts?

**Comment by NicolasBoumal** [comment]
Hello Bamdev,

With U = X - Y, the claimed equivalence is among these two expressions:

2*asinh(.5*sqrt(<U, U>_L))

acosh(-<X, Y>_L)

Do you see an issue with it? I did the math a while ago and didn't recheck it now. Numerically, they seem to match.

**Comment by kellertuer** [comment]
Ah with that approach I see that they are the same, I thought that U might have been log_XY; well. In Julia we use the acosh – so I would be interested in details about the numerical stability, too.

**Comment by NicolasBoumal** [comment]
On the sphere there is a clear-cut reason to favor `2*asin(.5*||x-y||)` over `acos(x'*y)` because the former is much more accurate when x, y are close to one another, and x, y can never be really far from one another. It's easy to setup a numerical experiment to verify this. And it's also easy to explain what's happening in a simplified model of the IEEE standard for double precision computation. Basically, the issue is that acos(t) has infinite derivative at t = x'*y = 1 (see https://www.wolframalpha.com/input/?i=plot+acos%28t%29) whereas 2*asin(.5*t) has derivative 1 at t = ||x - y|| = 0 (see https://www.wolframalpha.com/input/?i=plot+2*asin%28.5*t%29).

For hyperbolic space it's a bit more tricky because the manifold is unbounded, hence there ought to be a sweet spot where it's better to use one or the other, depending on how far apart they are. It'd be interesting to run the numbers of this.

**Comment by kellertuer** [comment]
Well this infinite derivative seems to hold, too, for acosh(t) and neither for 2*asinh(0.5t) https://www.wolframalpha.com/input/?i=plot+acosh%28t%29%2C+2*asinh%280.5*t%29 – but yes I also think for some large values of t acosh should be better.

**Comment by bamdevm** [comment]
Thanks for the answers. I am still not able to derive the equivalence. 

Approach 1
<u,u> = <x-y, x-y> = -2 - 2<x,y>.
theta = invcosh(-<x,y>) =>-<x,y> = cosh(theta)
=> <u,u> = -2 + 2*cosh(theta).

Approach 2
theta = 2invsinh(0.5 sqrt(<u,u>)) => 0.5*sqrt(<u,u>) = sinh(theta/2).
<u,u> = (2*sinh(theta/2))^2.

**Comment by kellertuer** [comment]
Your first approach can be used further as follows, see https://en.wikipedia.org/wiki/Hyperbolic_functions#Useful_relations, especially the difference of squares
cosh^2(x) - sinh^2(x) = 1, we will need it as -1+cosh^2(x) = sinh^2(x))
as well as the sum
cosh(x+y) = cosh(x)cosh(y) + sinh(x)sinh(y) 

Then from <u,u> = -2+2cosh(θ)
we get
1/2 <u,u> = -1 + cosh(2 * θ/2)
using x=y=θ/2 in the addition theorem we get
1/2 <u,u> = -1 + cosh^2(θ/2) + sinh^2(θ/2)
the first two summands are equal to the second (by the difference of squares) so we have
1/2 <u,u> = 2 sinh^2(θ/2)
divide by two and take the square root (sinh is nonnegative, since θ is)
1/2 sqrt(<u,u>) = sinh^2(θ/2)
hence
asinh(1/2 sqrt(<u,u>) = θ/2
and you are there at θ = 2 asinh(1/2 sqrt(<u,u>))

For this to hold we

**Comment by bamdevm** [comment]
Got it. In hindsight, I realised that I could have just substituted exponentials to find th equivalence. My bad. We can close the issue.

**Comment by kellertuer** [comment]
Until we have a good way to switch to the sinh, I think this is obsolete, yes. But thanks for the nice insight on an alternative formula.

**Comment by NicolasBoumal** [comment]
@kellertuer, currently, the default is to use the asinh formula. The acosh formula is in the comments of the code. I'm keen on keeping it that way. Alternatively, if someone identifies the proper threshold at which it is better to use one or the other, we could branch. I suspect the threshold is a distance of 1. That's a bit over twice as expensive though. I suppose we could have dist_small and dist_large functions that are pitched as being accurate for small or large distances, but...
