### ISSUE TITLE
fixedTTrank M.randvec / M.tangent / checkmanifold issue with dimension

### ISSUE THREAD

**Issue by NicolasBoumal** [NicolasBoumal/manopt#35]
The following code fails to produce 0 (or even something numerically close to zero):

```
clc; clear all; close all;
M = fixedTTrankfactory([2 2 2 2], [1 2 2 2 1]);
X = M.rand()
V = M.randvec(X)
norm(M.tangent(X, V) - V)  % should be zero, but it's 0.5
```

This might be related to the fact that when we run checkmanifold(M), we see that the dimension test fails. Perhaps the vectors generated by M.randvec(X) are not quite tangent?

**Comment by mpsenka21** [comment]
Your intuitions here are correct. My apologies for not noticing this earlier, but the random tangent vectors generated are not necessarily tangent.

M.randvec generates the tangent vector from a call to TTeMPS_tangent_orth(X, Xr), which generates a tangent vector structure w/ Gaussian random variational cores (V.dU), and doesn't necessarily ensure that they obey the gauge conditions.

The easiest fix I can think of is simply adding the line Z = tangent(X, Z) to the end of M.randvec, then renormalizing Z to be unit norm.

I have added that to my fork, and the code you presented works as intended, along with the dimension check for checkmanifold(M).

**Comment by NicolasBoumal** [comment]
Hmm, the code for `TTeMPS_tangent_orth(X, Xr)` suggests it should return a unit-norm tangent vector:

```
% default constructor which just returns a random unit norm tangent vector
    elseif nargin == 2
        % Y.U = xL.U;
        % Y.V = xR.U;
        Y.dU = cell(1, d);

        for i = 1:d
            Y.dU{i} = randn(size(Y.U{i}));
        end

        Y = TTeMPS_tangent_orth(xL, xR, Y);

        for i = 1:d
            Y.dU{i} = Y.dU{i} / (sqrt(d) * norm(Y.dU{i}(:)));
        end
```

It just prepares the terrain for a call with 3 inputs, which is also what M.proj uses.

Might there be an issue that the random tangent vector is represented with respect to Xr (right-orthogonalized) rather than wrt X? If so, this might have a number of ramifications.

**Comment by NicolasBoumal** [comment]
Additional point: `norm(M.proj(X, V) - V)` produces machine-precision zero, as intended.

**Comment by NicolasBoumal** [comment]
The issue might be related to the dimensions of my test case:

`M = fixedTTrankfactory([2 2 2 2], [1 2 2 2 1]);`

When I replace [2 2 2 2] by [3 3 3 3] the issue seems to disappear (and that's likely why we never saw that issue in our numerical experiments for the paper.)

Yet, this should be a legitimate manifold. An extreme case where we see the failure is for nxn matrices of rank n:

```
clear all; close all; clc;

M = fixedTTrankfactory([5 5], [1 5 1]);
checkmanifold(M);

X = M.rand();
V = M.randvec(X);
Va = M.tangent2ambient(X, V);
Vp = M.proj(X, Va);
V_min_Vp = M.lincomb(X, 1, V, -1, Vp);
M.norm(X, V_min_Vp)  % this isn't zero when we allow full rank objects
```

Admittedly, this is a bit of a corner case (nxn matrices of rank n form an open set of all nxn matrices), but it should be allowed.

**Comment by mpsenka21** [comment]
This was a tougher one to debug, but I think I have a proper answer now, which turned out to be a subtle detail for this edge case.

Recall that the formula for each dU{i} core looks something like $(I - U_i^L(U_i^L)^\top)(\ldots)$. Normally, U_i^L is a tall matrix, so even though $(U_i^L)^\top U_i^L = I$, we know that $(I - U_i^L(U_i^L)^\top) \ne 0$. However, for the case in your test, U_1^L is actually square (2 x 2), so $(I - U_i^L(U_i^L)^\top) = 0$, and thus $dU{1} = 0$. The manifold still doesn't have a trivial tangent space because none of $U_2^L, U_3^L, U_4^L$ are square, and this "defficiency" is accounted for in the dimension formula, so no problem there. However, there is a problem in how the TTeMPS method normalizes a random tangent vector:

'for i = 1:d
     Y.dU{i} = Y.dU{i} / (sqrt(d) * norm(Y.dU{i}(:)));
end'

Notably, this assumes none of the cores are zero. In your code, this snippet was then essentially taking dU{1}, which was already small on the order of machine precision, and dividing by machine precision, when the core should be left at 0.

To account for the possibility of some dU cores being 0 by definition, I adapted the above snippet as follows:

`% count number of nonzero dU cores
                % if manifold has positive dimension, num_nonzero > 1
                % with probability 1
                num_nonzero = 0;
                for k = 1:d
                    if norm(Y.dU{k}(:)) > 1e-14
                        num_nonzero = num_nonzero + 1;
                    end
                end

                % normalize vec to unit norm based on non-zero dU cores
                for k = 1:d
                    if norm(Y.dU{k}(:)) > 1e-14
                        Y.dU{k} = Y.dU{k} / (sqrt(num_nonzero) * norm(Y.dU{k}(:)));
                    end
                end
`

I force reset to the upstream manopt on my fork, and then implemented this change. After this change, the first snippet you posted runs as normal, and checkmanifold(M) still runs as normal.

Hopefully this does the trick!

**Comment by NicolasBoumal** [comment]
Thank you Michael, it seems this does the trick (PR #37 merged.)
