### ISSUE TITLE
Possible issue with randvec(.) For rotations matrices 

### ISSUE THREAD

**Issue by spencerkraisler** [NicolasBoumal/manopt#45]
Here is the following code:
`
G = rotations factory(3);
g = G.rand();
v = G.randvec(g)
`
When ran, I found that v is a skew-symmetric matrix, which is a tangent vector at the identity of SO3. However G.randvec() shouldn't be a skew-symmetric matrix, it should be v=g*xi, where xi is some skew-symmetric matrix.

**Comment by kellertuer** [comment]
Hi,
the resulting skew-symmetric matrix is correct. It mainly depends on how you store (or mathematically: represent) the tangent vector. Since (mathematically) a tangent vector “knows” its base point, the multiplication by `g` is a bijection and you can store either `v` or `ξ` (in your notation).
The advantage of just storing `ξ` is that several computations get easier, most prominently parallel transport, which (transporting to some `h`) is two matrix multiplications when using `v` as representation, and the identitiy for `ξ`.

Thats why in Manopt tangent vectors to the rotations manifold are stored in the Lie algebra (or tangent space at the identity), see also the note in the docs at

https://www.manopt.org/manifold_documentation_rotations.html

**Comment by spencerkraisler** [comment]
Ah that makes sense, and I appreciate that it’s done this way. Dealing with vectors in the Lie algebra is overall simpler, though it would be nice to have seen this in the tutorial (maybe I missed it?) Is it implemented this way for manifolds other than Lie groups too?

**Comment by kellertuer** [comment]
Which tutorial are you referring to with “the tutorial”?

For manifolds other than Lie groups, to me it would not be clear what the Lie algebra (or the tangent space at the identity) would be since neither exist, so “this way” not. In general, sure, if there is a representation that is beneficial, it should also be used.

**Comment by spencerkraisler** [comment]
By tutorial, I was referring to [this](https://www.manopt.org/manifold_documentation_rotations.html) webpage. I should add I do research with Lie groups, so yes I understand this is property unique only to Lie groups. I asked since with matrix manifolds, there could be many different ways to represent tangent vectors in better formats (like here for instance) and I was just curious if this was done for other manifold classes.

**Comment by kellertuer** [comment]
I only know of one manifold, where there is a specific different representation of tangent vectors – fixed rank matrices.
For others I really don't know.

On the page you linked the representation is explained in the blue box.

Thanks for the feedback, I am actually not contributing that much to this project (I think I wrote a function or two), since I mainly work in Julia with the packages https://github.com/JuliaManifolds (including Manopt.jl).

**Comment by spencerkraisler** [comment]
Ah I missed that, thank you.
