### ISSUE TITLE
Long clone times

### ISSUE THREAD

**Issue by jbriales** [NicolasBoumal/manopt#6]
Hi everyone!
I noticed manopt may take a long time to clone. Looking closer at the repo distribution, I see most of the content (22.5/24.8MB) is due to web/ and releases/. This is quite inconvenient for people (like me) packaging manopt as a local submodule in their projects (for solving dependencies).
Given the size of this project, I think it might be great to move those two heavy components (not directly related to the manopt functionality) to independent repositories (maybe NicolasBoumal/manopt-web and NicolasBoumal/manopt-releases). Worst case you can have those repositories as submodules in NicolasBoumal/manopt, although I would discourage that altogether.
Let me know what you think :)

**Comment by NicolasBoumal** [comment]
Hello again Jesus,

I went ahead and did the following:

1) I filter-branch'd /releases into a new repo, called manopt-releases; then I removed /releases from the main manopt repo. I did not add it back as a submodule, because we don't really need it for anything: it's just for safe-keeping. I also changed the release script accordingly.

2) I created a new repo called m2html (that's the third-party package I use to generate Matlab documentation), moved the m2html code there (it was formerly in manopt/reference/m2html), and finally added m2html as a submodule of manopt. This means that now, by default, when you clone manopt it won't pull the m2html code (you'll just get an empty folder unless you explicitly pull from there). And that's just as well, because manopt users should never need that code anyway.

Having removed /releases already reduces the size of the repo quite a bit. Admittedly, /web is the bigger one: I didn't make any changes to that one yet because ramifications run deeper Hoping you'll have some insight to share on that, re my previous message.

Best,
Nicolas

**Comment by NicolasBoumal** [comment]
Hello Jesus,

I now filter-branch'd /web out of the manopt repo and into a new repo called manopt-web.

For now, I also activated GitHub Pages on manopt-web to see how it works. If it works well, I will try to redirect manopt.org to the corresponding url, i.e., [https://nicolasboumal.github.io/manopt-web/](https://nicolasboumal.github.io/manopt-web/) -- still need to figure that out.

I deleted /web from the main manopt repo, and it seems that there is no need to add it as a submodule. The reason I was considering that is because it would have given a nicer url, namely, https://nicolasboumal.github.io/manopt/ (not manopt-web), but in retrospect I think I now understand that the proper way would have been to create a repo called manopt.github.io instead of manopt-web. If I can manage to connect manopt.org to it anyway, it doesn't matter.

One observation though: it seems that when I clone the manopt repo, it's still large even though I removed /web and /releases. I suspect that's because the history of those folders is still in there, and that gets cloned as well. Is there any way to deal with that?

Best,
Nicolas

**Comment by NicolasBoumal** [comment]
So, apparently, that thing about naming the repo manopt.github.io might be incorrect: that might be only for personal / organization webpages, as opposed to project webpages which is the case here.

It seems that the proper way might have been to simply create a new branch called gh-pages, and to commit the website only to that branch rather than to the master branch. If clones indeed only copy the master branch, than that would avoid copying the website documents. Not sure if that's accurate. In any case, having things in two different repos is not a big deal.

**Comment by NicolasBoumal** [comment]
(I seem to be getting some issues with HTTPS, in that when I connect to the website a first time I'm told it's not secure, but then subsequent connections are fine; not too sure if that was a fluke or if something is misconfigured.)

**Comment by jbriales** [comment]
Hi Nicolas! Sorry for the delay in replying...
I see you already addressed many of the steps involved.

Regarding why keeping /web and /releases independent and not as submodules, it was mainly for the sake of keeping the repository as minimal as possible (that is, reduced to the actual functionality for manopt users and almost nothing else :smile:)

Unfortunately I have zero experience on using GitHub Pages. It is in my long term to-do list to learn about it, but I never got the opportunity/urgency to do it. I already see from your comments that you figured out way more details than I knew about (like having a gh-pages branch, which I have seen elsewhere). There must be plenty of examples, I checked e.g. [the OpenGV library](https://github.com/laurentkneip/opengv).
As you say, having everything web-related in gh-pages would keep the default master clone light.
I see the web folder is actually still in the main repository, so if you want to move web from there to a gh-pages branch, that should be doable.

As for the HTTPS issue, it also appears as Not secure for me. Otherwise I can access it. But I don't know much about developing/maintaining websites :(

Finally, about the clone size, you suspected right. With the changes you did you cleaned the current structure (which is already good, ensuring that it keeps scalable e.g. adding new release backups in the separate repository), but the previous git history still holds all those files. When you clone master from the repository, the .git folder contains all the information gathered in master through history.
In order to actually decrease the current repository size, you need to REWRITE HISTORY, which comes with some caveats. Yet, again, it's doable. In this sense, I'd recommend:
- Have a look at [this doc](https://help.github.com/articles/removing-sensitive-data-from-a-repository/), which gives a full perspective on the approach, involved tools, caveats and workarounds.
- For removing a complete directory from history, check [this stackoverflow answer](https://stackoverflow.com/a/18129693) (I have used it before myself).
  The key step is doing:
  `git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch <directory_to_remove> -r' --prune-empty --tag-name-filter cat -- --all`
  This basically creates a list of all files removed in the directory and forces their deletion across history with `filter-branch`.
  And later `git push origin master --force`, where --force will be necessary to crush the Github repository content with the new content and history in your local repository.
In any case, be careful when doing anything with '--force'. Always make sure you understand (moderately at least!) what's going to happen, and create a local backup copy of the entire repository before doing any hard change, just in case.

Let me know if you have any further questions or I can help anyhow! :+1:

**Comment by NicolasBoumal** [comment]
Hello Jesus,

Thanks for your response.

> I see the web folder is actually still in the main repository

That was an oversight on my part, I forgot to push changes on my computer. It's resolved now: /web is no longer on the master branch of manopt; all web files are on manopt-web (with history preserved.)

> As for the HTTPS issue, it also appears as Not secure for me. Otherwise I can access it.

Did you mean that your browser asked you to explicitly allow it to go to manopt.org without encryption, or did you mean that you get to the website directly, only your browser indicates with a logo in the url field that the connection is not secure?

> In order to actually decrease the current repository size, you need to REWRITE HISTORY, which comes with some caveats.

I suspected as much. Thanks for the instructions -- I will consider it, but, as you said, I should be careful :).


As a side note, I contacted a few manopt users from China, and they all confirmed they can now access the website :).

(Just saw now that the domain name started redirecting to the former hosting service (which is apparent because there I moved all files in a "backup" folder), which is very odd... perhaps I need to wait 24h for the DNS update to propagate.)

Thanks!
Nicolas

**Comment by NicolasBoumal** [comment]
Hello Jesus,

I'm finally getting back to this. I let it sit for a while because this seemed like risky business and not particularly urgent, but let's give it a try. I'm keeping track of everything here for futur reference.

I checked out my local master branch and made sure there were no dangling, uncommitted changes etc.

I rank this to check the size of the repo:
`git count-objects -vH`
The result was: about 40Mb in the pack, and 40Mb of garbage.

Following your recommendations, I ran these commands to erase folders web/ and releases/ recursively:

`git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch web -r' --prune-empty --tag-name-filter cat -- --all`
`git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch releases -r' --prune-empty --tag-name-filter cat -- --all`

Then I ran the garbage collector:
`git gc --aggressive`

This generated the following message:
"Unlink of file '.git/objects/pack/pack-###some code###.pack' failed. Should I try again? (y/n)"
Answering "y" kept failing. Closing Matlab resolved this issue.

Then I re-assessed the size of the repo:
`git count-objects -vH`
The good news is that the garbage was gone, but the pack was still pretty much occupying 40Mb, not much less.

To figure out what is taking space, I first ran this command, taken from a conversation [here](https://github.com/18F/C2/issues/439):
`git verify-pack -v .git/objects/pack/pack-9e055e4443f6be5bd8d24e3810b2381e3d68492f.idx | sort -k 3 -n | tail -10`

Then, I ran this command a few times using the sha1's that came out of the previous command:
`git rev-list --objects --all | grep [first few chars of the sha1 from previous output]`

It turned out that a long long time ago there was a repository called publicrelations/ that contained a video, so I removed that too:
`git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch publicrelations -r' --prune-empty --tag-name-filter cat -- --all`

This this again:
`git gc --aggressive`
`git count-objects -vH`

But the pack still occupies ~40Mb...

I thought maybe I need to force push for things to somehow "sink in":
`git push origin master --force`

But it doesn't have an effect on the pack size.

I'll try to finish this later. Hopefully, this didn't break anything.

**Comment by NicolasBoumal** [comment]
I think the actual size of the repo may have been reduced as planned, even though the pack size on my local disk is still ~40Mb (in fact, it appears to go up by some amount after each filter-branch).

As it stands, SourceTree gives me a weird looking history where each commit appears twice:

![image](https://user-images.githubusercontent.com/7525898/82441608-2c623300-9a6c-11ea-94b4-1806763237d9.png)

Maybe I need to delete my local copy and clone from remote to reset this. I'll try this next.

**Comment by NicolasBoumal** [comment]
Deleting my local files and cloning anew from remote did not solve the issue: each commit still appears twice, and the pack size is about 41Mb (a bit larger than before the all the changes described here). On the bright side, it doesn't seem like I broke anything, but hard to say for sure.

**Comment by NicolasBoumal** [comment]
Ok, the double history appears because there is a remote branch whose history hasn't been rewritten. Somehow, that branch kept all the tags, so I am moving them to the current master branch one by one.

**Comment by NicolasBoumal** [comment]
There are substantial issues now with the branch bmsymfixedrankpolarfactory which corresponds to an old pull request that was never merged. I should have handled this before any history rewrites -- won't happen twice.

**Comment by NicolasBoumal** [comment]
In order to salvage the commits from Bamdev's PR #12 , I followed the instructions here:

http://blog.asquareb.com/blog/2014/06/19/making-a-git-pull-request-for-specific-commits/

Here is what I effectively did:

- Check out master branch.
- Create new branch (and check it out): bmsymfixedrankpolarfactory_new
- Add specific commits to it that correspond to the changes that happened in the former bmsymfixedrankpolarfactory branch; This should work because those changes affected a very limited number of files that do not exist in any other branch:

`git cherry-pick 0cb5565c56cd040ab45908719866c3995d2e7d51^..2d4dc6aec4a6da0d4ca07680dd3e51eae5f8d47a`
`git cherry-pick d439a395a3bc7a2bf894419c6265f3dbd67b0a78`
`git cherry-pick ceb33881742b97a1b6a6d285e179a5c6488efbb5`
`git cherry-pick 80a83e9d6a6a9fb8b601eb8978063308397ffacf -m 1`
`git cherry-pick 3e0186981a84e7923d4606143067b209a0505572^..2c2a47878c2bc8e1fe458d4ebe16df0772a1574d`

(The ^ before .. indicates that the first commit should be included too.)

(The "-m 1" option is because that commit is a merge, so we have to specify who's the mainline, that is, specify the parent; which parent is which can be seen in SourceTree by selecting the merge commit. That particular command said that this commit is empty, which seems fine.)

(There was some trial-and-error involved, in particular because there is a merge into that branch we try to save.. anyway: "git cherry-pick abort" is very helpful to stop and try something else.)

PR #24 is the new home for those changes that were salvaged.

**Comment by NicolasBoumal** [comment]
The old branch from PR #12 is now deleted (after moving all relevant contents to PR #24).

This does indeed clean up the "double history" issue as pictured in the screenshot above.

However, even after an aggressive garbage collection, the pack size is still about 40Mb (it went down slightly from the ~41Mb). I don't know what I can do about this now. Maybe this time it is an issue about my local copy that no longer exists on the remote..

**Comment by NicolasBoumal** [comment]
This [stack overflow discussion](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history/42544963#42544963) has a great command line to get a human-readable list of everything in a repo, sorted by size:

```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

Run on the current version of Manopt, it suggests that the largest file is 93Kib, which strongly suggests that there is something wrong with my local pack file. And indeed, cloning the manopt repo from remote to a separate local folder, I get a small pack file now: the full folder is ~3Mb. I'm closing this issue now.

Side note: tools such as Git Extensions also allow to get that list with one of the tools: it's much slower, but allows one to delete a file from the repo too (so, I guess, rewriting history as needed).
