### ISSUE TITLE
Visibility of further (external) algorithms

### ISSUE THREAD

**Issue by kellertuer** [NicolasBoumal/manopt#61]
I recently came across a statement in (added link  https://arxiv.org/abs/2304.01467 - that I forgot in the first version), that claimed “there is no publicly released Riemannian solvers for [constraint problems].” when they talked about about ALM/EPM/FW.  While they might not have speant so much time researching this, currently ALM/EPM are in [this repository from Changshuo Liu](https://github.com/losangle/Optimization-on-manifolds-with-extra-constraints).
I today also came across [this interior point method](https://github.com/GALVINLAI/RIPM) code, which looks interesting.

Sure integrating both here bears its problems maybe, but they could be linked in the docs somewhere?

**Comment by NicolasBoumal** [comment]
(I imagine the missing link in your first sentence is [https://arxiv.org/abs/2304.01467](https://arxiv.org/abs/2304.01467).)

It's true that such external packages sometimes lack visibility, but I'm still in favor of keeping them separate from Manopt itself, in the spirit of (aiming to) do one thing well.

Googling "constrained optimization on manifolds" (without being logged to my google account) does bring up several relevant packages on page 1, so I think it's visible enough for now.

**Comment by xnchxy** [comment]
Thank you so much for your valuable comments. We apology that we have unintentionally overclaimed our results. To address this issue, we have added appropriate citation and description of your solver in our paper. The new version of our paper will replace the old one on arXiv soon. On the other hand, we are going to conduct additional experiments to illustrate the numerical comparison between your solver and our approach. Since they are coded in different language, it may take sometime. 

We highly value the contributions in the work (Liu-Boumal, Applied Mathematics & Optimization, 2020, 82: 949-981), and if you have any additional concerns, please do not hesitate to contact us.

Authors of arXiv paper 2304.01467.

**Comment by kellertuer** [comment]
Oh, I did not mean to value your results. They might be well-done in the Euclidean sense (I personally would not test that many commercial solvers you seem to have checked); I was mainly surprised that you spent most of the motivation on manifolds, but your algorithms and numerics are (as far as I could see) unrelated to that comparison. As stated above, that might have been visibility, but Nicolas pointed out that google should be well suited there as well.

Sure, these different languages are sometimes time-consuming then (I do programming in Julia for example), but great that you are planning to do comparisons.
